name:               "康冰的个人博客"
description:        "Just do it"

url:                ""
author:             "kangbing"
email:              "kangbingbj@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "kangbingbj@gmail.com"
github:             "Mringkang"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "bing.kang.92"

disqus_shortname:   "thinker3197"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "关于"
    href:           "/about"
  - name:           "Hello Word"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate