name:               "康冰的个人博客"
description:        "Just do it"

url:                "https://avatars0.githubusercontent.com/u/15312953?v=3&u=fe8be8bda3cafac8ff163b25127cef6dda51b7d0&s=400"
author:             "kangbing"
email:              "kangbingbj@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "kangbingbj@gmail.com"
github:             "Mringkang"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "bing.kang.92"

disqus_shortname:   "thinker3197"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           7
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate