name:               "kangbing"
description:        "The world of programming is fascinating"

url:                ""
author:             "kangbing"
email:              "kangbingbj@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "kangbingbj@gmail.com"
github:             "Mringkang"
pinterest:          ""
linkedin:           ""
facebook:           "bing.kang.92"

disqus_shortname:   "kangbing"

background:         "http://apple.wallpapersfine.com/wallpapers/preview/1242x2208/w-9363.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Hello Word"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate